# Generated by Django 6.0.1 on 2026-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_uuid_alter_equipmentstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='athlete_number',
            field=models.CharField(max_length=15),
        ),
    ]
