# Generated by Django 6.0.2 on 2026-02-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_athlete_number'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.category'),
        ),
    ]
