# Generated by Django 6.0.3 on 2026-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
