# Generated by Django 6.0.3 on 2026-03-21 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_equipment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypeProperty',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
            ],
        ),
    ]
