# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipmenttypeproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='legal',
            field=models.BooleanField(default=False),
        ),
    ]
