# Generated by Django 6.0.3 on 2026-03-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('equipment', '0007_equipment_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='active_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
