# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_equipment_location_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='in_cart',
        ),
    ]
