# Generated by Django 6.0.1 on 2026-01-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='details',
            new_name='detail',
        ),
    ]
