# Generated by Django 6.0.1 on 2026-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredproperty',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='measuredproperty',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='measurementstatus',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='measurementstatus',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
